kibot:
  version: 1

preflight:
  run_erc: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  - name: Print Schematic
    comment: Print Schematic (PDF)
    type: pdf_sch_print

  - name: Print Board
    comment: Print Board (PDF)
    type: pdf_pcb_print
    layers: all

  - name: STEP File
    comment: Generate 3D STEP Model
    type: step

  - name: Gerbers
    comment: Generate Gerbers
    type: gerber
    dir: gerbers
    layers: all

  - name: Drills
    comment: Generate drill files
    type: gerb_drill
    dir: gerbers
    options:
      map:
        output: ''
        type: gerber
