name: Release

# Either push a new tag in the form v1.2.3
# or manually trigger the job with version 1.2.3 and a tag will be created
on:
  create:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: '"major", "minor", "patch" or "1.2.3" - leave empty for "patch"'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Sets RELEASE_VERSION to be refs/tags/v<version> -> <version>
      - name: Set env (tag pushed)
        if: github.event_name == 'create'
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/tags/v})
      - name: Set env (manually triggered)
        if: github.event_name == 'workflow_dispatch'
        run: echo ::set-env name=RELEASE_VERSION::${{ github.event.inputs.version }}

      # Pass ERC & DRC
      - name: Check schematic & board for errors
        uses: nerdyscout/kicad-exports@v1.1
        with:
          cmd: report
          dir: output
          board: lab68.kicad_pcb
          schematic: lab68.sch

      # Bump version
      - name: Bump version on the silkscreen
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -Ei "s/lab68 v[0-9]+\.[0-9]+ by dzervas/lab68 v${{ env.RELEASE_VERSION }} by dzervas/" lab68.kicad_pcb || exit 1
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git diff
          git add lab68.kicad_pcb
          git commit -m "Bump board version to ${{ env.RELEASE_VERSION }}"

      # Create tag if necesary
      - name: Tag release (manually triggered)
        if: github.event_name == 'workflow_dispatch'
        run: git tag v${{ github.event.inputs.version }}
      - name: Push changes (manually triggered)
        if: github.event_name == 'workflow_dispatch'
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Generate release artifacts
      - name: Generate schematic PDF & SVG
        uses: nerdyscout/kicad-exports@v1.1
        with:
          cmd: schematic
          dir: output
          board: lab68.kicad_pcb
          schematic: lab68.sch
      - name: Generate board PDF
        uses: nerdyscout/kicad-exports@v1.1
        with:
          cmd: kicad-board
          dir: output
          board: lab68.kicad_pcb
          schematic: lab68.sch
      - name: Generate gerbers, drills, etc.
        uses: nerdyscout/kicad-exports@v1.1
        with:
          cmd: fabrication
          dir: output
          board: lab68.kicad_pcb
          schematic: lab68.sch

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
          tag_name: v${{ env.RELEASE_VERSION }}
          fail_on_unmatched_files: true
